### ISSUE TITLE
[아바타 상세보기 - 댓글 더보기] 댓글 더보기를 두번 눌렀는데 에러가 났어요 

### ISSUE THREAD

**Issue by sinqua** [sinqua/ipoom#151]
아마 5개씩 불러와서 문제가 되는 듯 합니다. 5의 배수가 아닐때 이상해지나봐요.

![image](https://github.com/sinqua/ipoom/assets/29921733/f0ccd173-d211-48ad-bac7-6f16fd3664d4)

**Comment by sunyongj1004** [comment]
댓글 순서를 최신순으로 정렬하기
댓글 작성 시간 보여주는 방식 수정
