### ISSUE TITLE
[내비게이션] 200 OK 신호를 받아오지만, 페이지 리다이렉션이 되지 않을 때가 있음

### ISSUE THREAD

**Issue by sinqua** [sinqua/ipoom#190]
늘 일어나는 문제는 아님. 하지만 종종 그럴때가 있으며, 발생하면 존나 짜증남.

**Comment by sinqua** [comment]
[고병국] [오전 11:03] https://redirect.li/http/headers/x-vercel-cache/

**Comment by sinqua** [comment]
"TREE MISMATCH"  -> Nextjs rehydrate 과정을 실패함

**Comment by sunyongj1004** [comment]
https://www.reddit.com/r/nextjs/comments/o16ep3/strange_issue_in_production_build_links/

**Comment by sinqua** [comment]
링크 컴포넌트 아래에 이미지 태그를 넣지 말아야 하는 건가요?

**Comment by sunyongj1004** [comment]
Link 태그 자체에 대한 문제를 말하고 있는데, 2년 전 자료라서 일단은 보류 후 다른 자료 찾는 중

**Comment by sunyongj1004** [comment]
멈추고나면 Link에 마우스를 올리기만 해도, Tree Mismatch가 찍힘

**Comment by sinqua** [comment]
https://github.com/nuxt-modules/supabase/issues/188

**Comment by sinqua** [comment]
![image](https://github.com/sinqua/ipoom/assets/29921733/42d3297d-2e3d-4cef-9987-ab4932548ced)
정상적으로 작동할 때는 개별 웹페이지의 용량이 50 바이트 이내. 

![image](https://github.com/sinqua/ipoom/assets/29921733/01af38b1-b727-4949-861d-63319f3efcab)
비정상적으로 작동할 때는 개별 웹페이지의 용량이 1000 ~ 2000바이트.

**Comment by sinqua** [comment]
![image](https://github.com/sinqua/ipoom/assets/29921733/be33ef82-cc1d-4879-b8da-1f885a4f4299)
자 이게, 서버에 렌더링된 페이지는 유효기간이 존재하고, 그 시간 이후에는 새롭게 렌더링이 된다. 이때부터 문제가 생기게 된다.

**Comment by sinqua** [comment]
route.refresh() 메서드로 서버사이드렌더링 결과를 무시하도록 선택했습니다. 그 대신, 리액트는 더이상 하이드레이션이나 프리페치기능을 활용할 수 없게 되었습니다.
